# -*- coding: utf-8 -*-
"""Copy of hw17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wO8OeRWM63o-oMPmqaSVyewuvwetth0Q
"""

import random

def func(x,n):
  sum = 0
  if n < 0:
    raise Exception('Sorry, n must be a non negative integer!')
  else:
    for i in range(n+1):
      sum+=(pow(x,i))

  return int(sum)

def formula(x,n):
  sum = 0
  if n < 0:
    raise Exception('Sorry, n must be a non negative integer!')
  elif x == 1:
    sum = n+1
  else:
    sum = (1-(pow(x,n+1)))/(1-x)

  return int(sum)

def test(x,n):
  sum_func = 0
  if n < 0:
    raise Exception('Sorry, n must be a non negative integer!')
  else:
    for i in range(n+1):
      sum_func+=(pow(x,i))

  if x == 1:
    sum_formula = n+1
  else:
    sum_formula = (1-(pow(x,n+1)))/(1-x)

  if sum_formula == sum_func:
    print('Equivalent')
  else:
    print('Not equivalent')

  return int(sum_formula), int(sum_func)

x = random.randint(0,10)
n = random.randint(0,10)
print(f'{x},{n}')
test(x,n)